install: true  
script:  
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo -e $RESIN_DEPLOY_KEY > id_rsa
  - chmod 0600 id_rsa
  - ssh-add ./id_rsa
  - cat resinkey >> ~/.ssh/known_hosts
  - git remote add resin gh_mckaycr@git.resin.io:gh_mckaycr/sonicdipstick.git
  - git push resin master