version: '2'
volumes:
    resin-data:
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - 'resin-data:/data'
    privileged: true
  mongdb:
    image: nonoroazoro/rpi-mongo
    ports:
    - "27017:27017"
    volumes:
    - 'resin-data:/data/db'