version: '2'
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - ./data:/data
    privileged: true
  mongdb:
    image: nonoroazoro/rpi-mongo
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db